name: Repository Dispatch
on:
  repository_dispatch:
    types: [pybuild]
jobs:
  pybuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login the Docker service
        uses: azure/docker-login@v1
        with:
          login-server: registry.cn-hongkong.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_REGISTER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REGISTER_PASSWORD }}
      - run: make pybuild
