name: release-pybuild

on:
  push:
    tags:
      - 'release-pybuild-v*'

jobs:
  release:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@master
    - uses: azure/docker-login@v1
      with:
        login-server: registry.cn-hongkong.aliyuncs.com
        username: ${{ secrets.ALIYUN_DOCKER_REGISTER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_REGISTER_PASSWORD }}

    - name: Push the image to aliyun register
      run: make pybuild




