name: release-gobuild

on:
  push:
    tags:
      - 'release-gobuild-v*'

jobs:
  release:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@master
    - uses: azure/docker-login@v1
      with:
        login-server: registry.cn-hongkong.aliyuncs.com
        username: ${{ secrets.ALIYUN_DOCKER_REGISTER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_REGISTER_PASSWORD }}

    - name: Push the image to aliyun register
      run: make gobuild

    - name: Login hangzhou docker register
      uses: azure/docker-login@v1
      with:
        login-server: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_DOCKER_REGISTER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_REGISTER_PASSWORD }}

    - name: Push the image to hangzhou aliyun register
      run: |
        docker tag registry.cn-hongkong.aliyuncs.com/strengthening/gobuild registry.cn-hangzhou.aliyuncs.com/strengthening/gobuild
        docker push registry.cn-hangzhou.aliyuncs.com/strengthening/gobuild


